apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Nfs
metadata:
  name: cluster-nfs
spec:
  storageClass: cluster-nfs
  provisionerAPI: example.com/nfs
  backingStorage:
    pvcName: export-nfs-block
    storageClass: ibmc-vpc-block-general-purpose
    storageSize: 10Gi
