apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nfs.ibmcloud.ibm.com
spec:
  group: ibmcloud.ibm.com
  names:
    kind: Nfs
    listKind: NfsList
    plural: nfs
    singular: nfs
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.capacity
      name: Capacity
      type: string
    - jsonPath: .spec.storageclass
      name: StorageClass
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Nfs is the Schema for the nfs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NfsSpec defines the desired state of Nfs
            properties:
              backingStorage:
                description: BackingStorageSpec defines the desired state of the Backing
                  Storage
                properties:
                  pvcName:
                    type: string
                  storageClass:
                    type: string
                  storageSize:
                    type: string
                type: object
              provisionerAPI:
                default: example.com/nfs
                type: string
              storageClass:
                default: example-nfs
                type: string
            type: object
          status:
            description: NfsStatus defines the observed state of Nfs
            properties:
              accessMode:
                type: string
              capacity:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
